apiVersion: batch/v1
kind: Job
metadata:
  name: onlineshop-job
spec:
  template:
    spec:
      containers:
      - name: onlineshop-job
        image: yash5090/onlineshop:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
