apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlineshop-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: onlineshop
  template:
    metadata:
      labels:
        app: onlineshop
    spec:
      containers:
        - name: onlineshop
          image: yash5090/onlineshop:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
